sonar.projectKey=go-project-244
sonar.organization=misterDillett
sonar.host.url=https://sonarcloud.io

sonar.language=go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out